[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[dev]
  targetPort = 3000
  functionsPort = 9999

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
